### ISSUE TITLE
Wsparcie systemów mobilnych

### ISSUE THREAD

**Issue by xartuu** [ccwe/frekwencja#1]
**Cześć!**
Bardzo przydatna aplikacja. Szkoda, że udostępniliście tylko wersję na systemy operacyjne na komputerze. Chodząc do szkoły (my, uczniowie) korzystamy z telefonów komórkowych - najczęściej jest to Android albo IOS. Dlatego super byłoby otrzymać wersje tej aplikacji na systemy mobilne, żeby mieć ją zainstalowaną w telefonie! Na przerwie moglibyście sprawdzić frekwencję czy proponowane oceny.

Z niecierpliwością czekam!

**Comment by kuba2k2** [comment]
Cześć @xartuu,
Być może w tej sytuacji pomoże ci moja otwartoźródłowa apka: https://szkolny.eu/pobierz
